services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MARIADB_DATABASE: ${DB_NAME:-videos}
      MARIADB_USER: ${DB_USER:-app}
      MARIADB_PASSWORD: ${DB_PASSWORD:-apppass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-change_me}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-videos}
      DB_USER: ${DB_USER:-app}
      DB_PASSWORD: ${DB_PASSWORD:-apppass}
      UPLOAD_DIR: /data/uploads
      VIDEO_DIR: /data/videos
      TMP_DIR: /data/tmp
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    volumes:
      - app_data:/data
    ports:
      - "3000:3000"

volumes:
  db_data:
  app_data:
